Repository yklym/telegramGameBot, pull requests merged in 2020-06, with the labels that each got.

#4 Dev
  data/commands_list.py
  data/text/chat.py
  data/text/command.py
  data/text/game.py
  data/text/user.py
  db/dbController.py
  db/models/game.py
  db/models/user.py
  handlers/chat/default_commands.py
  handlers/chat/game.py
  handlers/shared/commands.py
  handlers/user/default_commands.py
  handlers/utils/filters.py
  test.py
Labels: deploy

#5 game creation
  data/keyboards/__init__.py
  data/keyboards/game.py
  data/text/default_commands.py
  data/text/game.py
  data/text/warnings.py
  db/dbController.py
  db/models/game.py
  handlers/__init__.py
  handlers/callbacks/__init__.py
  handlers/callbacks/game.py
  handlers/chat/game.py
  handlers/middlewares/auth.py
  handlers/shared/commands.py
  handlers/utils/game.py
Labels: deploy

#8 Interactive rules
  data/commands_list.py
  data/keyboards/commands.py
  data/text/rules.py
  handlers/callbacks/__init__.py
  handlers/callbacks/commands.py
  handlers/shared/commands.py
  handlers/utils/commands.py
  requirements.txt
  test.py
Labels: deploy, enhancement

#9 Dev
  README.MD
  data/commands_list.py
  data/config.py
  data/keyboards/game.py
  data/text/game.py
  data/text/warnings.py
  db/dbController.py
  db/models/game.py
  db/models/user.py
  handlers/callbacks/game.py
  handlers/chat/game.py
  handlers/utils/game.py
Labels: architecture, bug, db, deploy, invalid

#10 rules fixed
  handlers/callbacks/commands.py
  handlers/utils/game.py
Labels: bug

#11 Dev
  handlers/callbacks/commands.py
  handlers/utils/game.py
Labels: deploy

#12 rules fixed second time
  handlers/callbacks/commands.py
Labels: bug, deploy
